
services:
  app:
    image: gcr.io/instant-ground-442614-q5/spring-boot-app:latest
    container_name: spring-boot-app
    ports:
      - "8080:8080" # Exposes the app on port 8080
    environment:
      SPRING_PROFILES_ACTIVE: production # Optional, set if you use Spring profiles
