name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ dev, stage, prod ]
  pull_request:
    branches: [ stage, prod ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-app
          path: target/*.jar

  deploy-to-stage:
    needs: build-and-test
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-app

      - name: Deploy to Staging
        run: echo "Deploy to staging environment" # Replace with actual deployment steps

  deploy-to-prod:
    needs: deploy-to-stage
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://your-production-url.com
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-app

      - name: Deploy to Production
        run: echo "Deploy to production environment" # Replace with actual deployment steps