name: Build and Deploy to GCP

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: instant-ground-442614-q5
  GAR_LOCATION: asia-south1
  SERVICE: spring-boot-app
  REGION: asia-south1

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/instant-ground-442614-q5/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions@instant-ground-442614-q5.iam.gserviceaccount.com'

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v2
        with:
          registry: asia-south1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push Container
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: asia-south1-docker.pkg.dev/instant-ground-442614-q5/spring-boot-app:${{ github.sha }}
          cache-from: type=registry,ref=asia-south1-docker.pkg.dev/instant-ground-442614-q5/spring-boot-app:latest
          cache-to: type=inline

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: spring-boot-app
          region: asia-south1
          image: asia-south1-docker.pkg.dev/instant-ground-442614-q5/spring-boot-app:${{ github.sha }}

      - name: Show Output
        run: echo "Cloud Run service deployed at ${{ steps.deploy.outputs.url }}"
