name: Build and Deploy App

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: mvn clean package

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - run: gcloud auth configure-docker

      - name: Build and Push
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sample-project/demo-app:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sample-project/demo-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy demo-app \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sample-project/demo-app:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated