name: Dockerize Spring Boot App with MySQL

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Rakeshmp@04
          MYSQL_DATABASE: sample_db
          MYSQL_USER: root
          MYSQL_PASSWORD: Rakeshmp@04
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up JDK for Maven/Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the Spring Boot Application
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Set up Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t trial:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker tag trial:latest your-docker-username/trial:latest
        run: docker push your-docker-username/trial:latest

      # Run the Docker container
      - name: Run Docker Container with MySQL
        run: |
          docker network create springboot-network
          docker run -d --name mysql-container \
            --network springboot-network \
            -e MYSQL_ROOT_PASSWORD=Rakeshmp@04 \
            -e MYSQL_DATABASE=sample_db \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=Rakeshmp@04 \
            mysql:8.0
          docker run -d -p 8080:8080 --name spring-boot-app \
            --network springboot-network \
            -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/sample_db \
            -e SPRING_DATASOURCE_USERNAME=root \
            -e SPRING_DATASOURCE_PASSWORD=Rakeshmp@04 \
            trial:latest
